version: '3'
services:
  opensearch-1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-1
      - discovery.seed_hosts=opensearch-1
      - cluster.initial_master_nodes=opensearch-1
      - plugins.security.ssl.http.enabled=false
      - bootstrap.memory_lock=true           # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - 'http.port=9200'
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer        
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536       
    volumes:
      - opensearch-1:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-1:9200"]'    
    ports:
      - 5601:5601
    expose:
      - "5601"              
    networks:
      - opensearch-net
  data-prepper:
    container_name: data-prepper
    image: opensearchproject/data-prepper:latest
    volumes:
      - ./datapreper_cfg/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml:Z
      - ./datapreper_cfg/data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml:Z
    ports:
      - "21890:21890"      
    networks:
      - opensearch-net
    depends_on:
      - opensearch-1
  otel-collector:
    container_name: otel-collector
    image: opensearchproject/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yml" ]
    working_dir: "/project"  
    volumes:
      - ./datapreper_cfg/otel-collector-config.yml:/etc/otel-collector-config.yml:Z
    ports:
      - "14250:14250"
      - "14251:14251"
    depends_on:
      - data-prepper
    networks:
      - opensearch-net
  services-a:
    build: 
      context: .
      dockerfile: ./BackendBuild/Dockerfile
      args:
        - PROJ_NAME=ServiceA
        - BUILD_CONFIGURATION=Release      
    container_name: ServiceA
    environment: 
      Otlp__Endpoint: 'http://otel-collector:14251/'
      AppName: 'ServiceA'  
    entrypoint: "dotnet ServiceA.dll"    
    ports:
      - "8081:8080"
    networks:
      - opensearch-net
  services-b:
    build: 
      context: .
      dockerfile: ./BackendBuild/Dockerfile
      args:
        - PROJ_NAME=ServiceB
        - BUILD_CONFIGURATION=Release      
    container_name: ServiceB
    environment: 
      Otlp__Endpoint: 'http://otel-collector:14251/'
      AppName: 'ServiceB'
    entrypoint: "dotnet ServiceB.dll"          
    ports:
      - "8082:8080"
    networks:
      - opensearch-net  
  nginx:
    build:
      context: ./NginxGateway
      dockerfile: ./Dockerfile
    container_name: NginxGateway
    networks:
      - opensearch-net
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: WebApp
    networks:
      - opensearch-net
    ports:
      - "80:80"            
networks:
  opensearch-net:

volumes:
  opensearch-1:     